#!/bin/bash
# chkconfig: 95 10
# description: Oracle auto start-stop script \
# This script spelled out commands to start and stop and listener'a instance \
# The script will run at startup and shutdown of the operating system.

### BEGIN INIT INFO
# Provides:          Oracle
# Required-Start:    $network
# Required-Stop:     
# Default-Start:     2 3 4
# Default-Stop:      0 1 6
# Description:       Oracle DB
# Short-Description: Oracle service provided by Oracle
### END INIT INFO

# Change the value of ORACLE_HOME to specify the correct Oracle home
# directory for your installation.
#ORACLE_HOME=/opt/u01/app/oracle/product/12.1.0/db_1

# Set OWNER to the user id of the owner of the Oracle database in ORACLE_HOME.
OWNER=oracle
RETVAL=0

# Set shell limits for Oracle Database

ulimit -c unlimited
ulimit -d unlimited
ulimit -s 65536

if [ -s "/home/oracle/script/envoracle.cfg" ]; then
    source /home/oracle/script/envoracle.cfg
else
    echo "ERROR: file envoracle.cfg not exist,please set environment for oracle"
	exit
fi

if [ ! -f $ORACLE_HOME/bin/dbstart ]
	then
	echo "Oracle startup: cannot start"
exit 1
fi

#second version use runuser
#if [ ! "$2" = "ORA_DB" ] ; then
#      runuser -l $OWNER $0 $1 ORA_DB
#      if [ "$PLATFORM" = "Linux" ] ; then
#         touch /var/lock/subsys/oraservice
#      fi
#      exit 1
#   fi
#

case $1 in
'start')
#for oracle low 11        
		#su - $OWNER -c "$ORACLE_HOME/bin/lsnrctl start"
        su - $OWNER -c "$ORACLE_HOME/bin/dbstart $ORACLE_HOME"
		touch /var/lock/subsys/oraservice
#for runuser
		#$ORACLE_HOME/bin/dbstart $ORACLE_HOME &
		;;
'stop')
		su - $OWNER -c "$ORACLE_HOME/bin/dbshut $ORACLE_HOME"
        rm -f /var/lock/subsys/oraservice
#for oracle low 11   
		#sudo -u $OWNER -c "$ORACLE_HOME/bin/lsnrctl stop"
#for runuser
        #$ORACLE_HOME/bin/dbshut $ORACLE_HOME &
		;;
*)
        echo "usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit $RETVAL